### ISSUE TITLE
`%u` in format string produces `Int` argument

### ISSUE THREAD

**Issue by paulgessinger** [liamnichols/xcstrings-tool#22]
I would guess this should actually result in a `UInt` argument?

I'm guessing this is where this is currently decided:

https://github.com/liamnichols/xcstrings-tool/blob/7ca47645b648702e83e9463f1d7c850195bbd1f2/Sources/StringExtractor/PlaceholderType.swift#L13-L14

Is there any argument why `%u` should not result in `UInt` or is this a bug?

**Comment by liamnichols** [comment]
Thanks for raising this @paulgessinger! 

> I would guess this should actually result in a `UInt` argument?

I've never worked with `%u` before, but looking at some reference for `printf`, it seems that you are right: https://en.wikipedia.org/wiki/Printf#Type_field

I think that it would be fine to add a `uint` case to `PlaceholderType` and map to it from `"u"` 👍 

If you feel up for a Pull Request, that would be great! If not, I'll take a look when I get a bit of free time 🙂

**Comment by paulgessinger** [comment]
Happy to try a PR!

I'm struggling a bit to get the generated swift file since the test generator puts it in a temporary directory that gets deleted right after the test run it seems. 

I tried changing the target location to CWD temporarily but that seems to give an empty for somehow.

**Comment by liamnichols** [comment]
Ah yes, I will have to try and remember how I implemented the testing infra 😅 I'll add a note to write some instructions for future contributors 🙏 

- https://github.com/liamnichols/xcstrings-tool/issues/24

**Comment by liamnichols** [comment]
Thanks again @paulgessinger, this is released in [0.1.1](https://github.com/liamnichols/xcstrings-tool/releases/tag/0.1.1)
