### ISSUE TITLE
Permission error in Xcode Cloud

### ISSUE THREAD

**Issue by hiragram** [liamnichols/xcstrings-tool#35]
Hi,

Thank you for creating `xcstrings-tool`. 
It works fine on my macbook but not on Xcode Cloud.

<img width="1162" alt="スクリーンショット 2024-01-03 17 47 38" src="https://github.com/liamnichols/xcstrings-tool/assets/3433324/6b1f11f4-5fbc-4911-a5d7-28f34bc101bf">

( `Compose` is the name of my Swift package)

I am very new to build tools plugin mechanism. Do you have any ideas?

**Comment by liamnichols** [comment]
Hmm this is very strange. Unfortunately I have never used Xcode Cloud before so I am not completely sure what might cause this. 

I assume that you are experiencing this issue _after_ working around the plugin validation issues described on the [Swift forums](https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/7)?

At a guess, it might be related to how I create the output directory (XCStringsTool) for writing the generated source (Compose.swift):

https://github.com/liamnichols/xcstrings-tool/blob/ef4b152689b98cc2b741f7a194396a758385da72/Sources/xcstrings-tool/Utilities/ParsableCommand%2BUtilities.swift#L15

But I don’t know much about file/directory permissions to know if I need to give XCStringsTool more permissions or not?

**Comment by liamnichols** [comment]
Related (but no answer)? https://stackoverflow.com/questions/76317833/xcode-cloud-has-no-write-permission-when-running-swift-package-plugin

**Comment by liamnichols** [comment]
Also: https://stackoverflow.com/questions/77327297/ci-server-on-xcodecloud-using-rswift-stops-with-the-following-error-rswiftgener

**Comment by hiragram** [comment]
> I assume that you are experiencing this issue after working around the plugin validation issues described on the [Swift forums](https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/7)?

Yes. `IDESkipPackagePluginFingerprintValidatation` is enabled.

I am looking into stackoverflow which you've pointed out. Thanks.

**Comment by hiragram** [comment]
I have just found execution on local macbook emits warning about location of written files even if it succeeds. Output path may be incorrect. I am looking into it.

<img width="718" alt="image" src="https://github.com/liamnichols/xcstrings-tool/assets/3433324/2f29704c-962c-4c86-bde7-b5a5deda6d71">

**Comment by hiragram** [comment]
@liamnichols What is the purpose of this subdirectory? Is it required to work?

https://github.com/liamnichols/xcstrings-tool/blob/ef4b152689b98cc2b741f7a194396a758385da72/Plugins/XCStringsToolPlugin/Command%2BXCStringsTool.swift#L36-L38

btw, I guess this issue is caused by XcodeCloud-side bug so far. Sent feedback to apple.

**Comment by liamnichols** [comment]
I create the subdirectory based on the documentation in the [SE proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md): 

> ```swift
>     /// The path of a writable directory into which the plugin or the build
>     /// commands it constructs can write anything it wants. This could include
>     /// any generated source files that should be processed further, and it
>     /// could include any caches used by the build tool or the plugin itself.
>     /// The plugin is in complete control of what is written under this di-
>     /// rectory, and the contents are preserved between builds.
>     ///
>     /// A plugin would usually create a separate subdirectory of this directory
>     /// for each command it creates, and the command would be configured to
>     /// write its outputs to that directory. The plugin may also create other
>     /// directories for cache files and other file system content that either
>     /// it or the command will need.
>     var pluginWorkDirectory: Path { get }
> ```

**Comment by liamnichols** [comment]
Please also share the feedback number so that I can duplicate it 🙏

I found another post describing the same issue here (but no solution 🥲): https://developer.apple.com/forums/thread/725474

**Comment by hiragram** [comment]
Finally I've just found what causes this issue. https://github.com/liamnichols/xcstrings-tool/pull/36
