### ISSUE TITLE
Keys which are Swift keywords can't be compiled

### ISSUE THREAD

**Issue by HarshilShah** [liamnichols/xcstrings-tool#38]
If you have a localized string with a key named `continue`, `repeat`, or any other keywords, the generated Swift code just inserts them as is, and so the files don't compile. A workaround is to name these something else, such as `continueLabel`, but this could also be solved by escaping any keys which are known Swift keywords by wrapping them in backticks

**Comment by liamnichols** [comment]
Oh good spot! This shouldn't be too hard to fix. 

I wonder if SwiftSyntax has an enum/definition of reserved keywords to make it easy for us to figure out what needs escaping or not.

**Comment by HarshilShah** [comment]
Woohoo, thank you for the fix!

**Comment by liamnichols** [comment]
No worries! I just published the full 0.4.2 release with this fix now 👍
