### ISSUE TITLE
Set default value to be fallback documenting comment

### ISSUE THREAD

**Issue by mylogon341** [liamnichols/xcstrings-tool#68]
When option+click on a string, it would nice to be able to see the default value of the string for quick reference.
When a comment is set in the string catalog, this is the documenting comment, but I think setting the `defaultValue` as the fallback would be massively helpful, as it is in swiftgen, which is what I'm trying to move away from.

Thanks

**Comment by liamnichols** [comment]
Released in 0.3.0 🙏
